!$ElementBorderThickness = 2
!procedure $top_block_scheme()
    BorderThickness 2
    BorderColor black
    'FontColor red
!endprocedure

'povolení box v boxu
'!pragma teoz true 
skinparam {
    'BoxPadding 10
    'PageMargin 10
    titleFontSize 24
    'šířka textů spojnic
    maxMessageSize 260 
    'šířka poznámek
    WrapWidth 350 
    RoundCorner 8
    'odsazeni v bloku - vlevo vpravo
    'ParticipantPadding 20
    'odskok mezi bloky
    'BoxPadding 10

    'responseMessageBelowArrow true
    noteBorderThickness 1
    noteBackgroundColor #Ivory
    'noteBorderColor gray
    'noteFontColor black

    'AgentBorderThickness 5
    'ComponentBorderThickness 5
    'ObjectBorderThickness 5
    'SequenceDividerBorderThickness 3
    'DiagramBorderThickness 5
}

skinparam actor {
    $top_block_scheme()
    BackgroundColor SkyBlue
}

skinparam entity {
    $top_block_scheme()
    BackgroundColor #ff9c9c
}

skinparam boundary {
    $top_block_scheme()    
    BackgroundColor #ff9c9c
}

skinparam database {
    $top_block_scheme()
    BackgroundColor DarkKhaki
}

skinparam collections {
    $top_block_scheme()
    BackgroundColor Moccasin
}

skinparam participant {
    $top_block_scheme()
}

skinparam control {
    $top_block_scheme()
}

skinparam queue {
    $top_block_scheme()
}

skinparam sequence {
    'zarovnání textu
    'MessageAlign direction
    'MessageAlign center
    'šipky toku požadavku
    ArrowThickness 1.4
    ArrowColor DeepSkyBlue
    ActorBorderColor DeepSkyBlue

    'boxy životnosti
    LifeLineBorderColor black 
    LifeLineBorderColor #00729be8
    LifeLineBackgroundColor #A9DCDF
}

skinparam actor {
    BorderColor black
}

'skinparam actorStyle Hollow


<style>
footer {
    HorizontalAlignment right
}

sequenceDiagram {
    group {
        FontSize 14
    }
}
alt {
    'BackgroundColor red
}

</style>
